apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{"deployment.kubernetes.io/revision":"1"},"creationTimestamp":"2024-03-25T09:29:08Z","generation":2,"labels":{"app":"my-book"},"name":"evan-sample-evan-1711358948","namespace":"default","ownerReferences":[{"apiVersion":"webapp.my.domain.com/v1","blockOwnerDeletion":true,"controller":true,"kind":"Evan","name":"evan-sample","uid":"4ff272ff-8737-4a27-95ae-fe011029ccc8"}],"resourceVersion":"116876","uid":"84d28a29-0a7f-4545-a35b-d3690f0568b8"},"spec":{"progressDeadlineSeconds":600,"replicas":2,"revisionHistoryLimit":10,"selector":{"matchLabels":{"app":"my-book"}},"strategy":{"rollingUpdate":{"maxSurge":"25%","maxUnavailable":"25%"},"type":"RollingUpdate"},"template":{"metadata":{"creationTimestamp":null,"labels":{"app":"my-book"}},"spec":{"containers":[{"image":"evanraisul/book-api","imagePullPolicy":"Always","name":"my-book","ports":[{"containerPort":4444,"protocol":"TCP"}],"resources":{},"terminationMessagePath":"/dev/termination-log","terminationMessagePolicy":"File"}],"dnsPolicy":"ClusterFirst","restartPolicy":"Always","schedulerName":"default-scheduler","securityContext":{},"terminationGracePeriodSeconds":30}}},"status":{"availableReplicas":3,"conditions":[{"lastTransitionTime":"2024-03-25T09:29:19Z","lastUpdateTime":"2024-03-25T09:29:19Z","message":"Deployment has minimum availability.","reason":"MinimumReplicasAvailable","status":"True","type":"Available"},{"lastTransitionTime":"2024-03-25T09:29:08Z","lastUpdateTime":"2024-03-25T09:29:22Z","message":"ReplicaSet \"evan-sample-evan-1711358948-85df4b6bfc\" has successfully progressed.","reason":"NewReplicaSetAvailable","status":"True","type":"Progressing"}],"observedGeneration":2,"readyReplicas":3,"replicas":3,"updatedReplicas":3}}
  creationTimestamp: "2024-03-25T09:29:08Z"
  generation: 4
  labels:
    app: my-book
  name: evan-sample-evan-1711358948
  namespace: default
  ownerReferences:
  - apiVersion: webapp.my.domain.com/v1
    blockOwnerDeletion: true
    controller: true
    kind: Evan
    name: evan-sample
    uid: 4ff272ff-8737-4a27-95ae-fe011029ccc8
  resourceVersion: "117353"
  uid: 84d28a29-0a7f-4545-a35b-d3690f0568b8
spec:
  progressDeadlineSeconds: 600
  replicas: 4
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: my-book
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: my-book
    spec:
      containers:
      - image: evanraisul/book-api
        imagePullPolicy: Always
        name: my-book
        ports:
        - containerPort: 4444
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 3
  conditions:
  - lastTransitionTime: "2024-03-25T09:29:08Z"
    lastUpdateTime: "2024-03-25T09:29:22Z"
    message: ReplicaSet "evan-sample-evan-1711358948-85df4b6bfc" has successfully
      progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  - lastTransitionTime: "2024-03-25T09:46:15Z"
    lastUpdateTime: "2024-03-25T09:46:15Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 4
  readyReplicas: 3
  replicas: 3
  updatedReplicas: 3
