---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - webapp.my.domain.com
  resources:
  - evans
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - webapp.my.domain.com
  resources:
  - evans/finalizers
  verbs:
  - update
- apiGroups:
  - webapp.my.domain.com
  resources:
  - evans/status
  verbs:
  - get
  - patch
  - update
